spring.application.name=so_tro_online

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.datasource.url=jdbc:mysql://localhost:3306/quanlytro
#spring.datasource.username=root
#spring.datasource.password=johndoe@123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hikari config
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

# Spring Batch configuration - use lowercase table names to match your database
spring.batch.jdbc.table-prefix=batch_
spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=true

# MySQL specific settings for case sensitivity
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

#Twilio configuration
twilio.account-sid=${twilio.account-sid}
twilio.auth-token=${twilio.auth-token}
twilio.phone-number=${twilio.phone-number}


# Add component scan debugging
logging.level.org.springframework.context.annotation=DEBUG
logging.level.org.springframework.beans.factory.support=DEBUG

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
